# Generated by Django 4.2.2 on 2023-06-17 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jar',
            options={'verbose_name': 'Jar', 'verbose_name_plural': 'Jars'},
        ),
    ]
