# Generated by Django 4.2.2 on 2023-06-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jars', '0003_jar_monojarid'),
    ]

    operations = [
        migrations.AddField(
            model_name='jar',
            name='url',
            field=models.CharField(default='nothing', max_length=255),
            preserve_default=False,
        ),
    ]
