# Generated by Django 4.2.2 on 2023-06-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jars', '0004_jar_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jar',
            name='url',
        ),
        migrations.AlterField(
            model_name='jar',
            name='monoJarid',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
