# Generated by Django 4.2.2 on 2023-06-20 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jars', '0005_remove_jar_url_alter_jar_monojarid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jar',
            name='description',
        ),
        migrations.RemoveField(
            model_name='jar',
            name='name',
        ),
    ]
